spring.application.name=CRUD-Project1
spring.datasource.url=jdbc:postgresql://localhost:5432/Employee
spring.datasource.username=postgres
spring.datasource.password=Haseeb
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
